### ISSUE TITLE
Don't show the number of moves until all dices have landed

### ISSUE THREAD

**Issue by forteller** [Sothatsit/RoyalUrClient#71]
Small annoyance in this otherwise amazing game/site: The number below the dices tells you the number of moves you get before the last dice has "landed" (image + sound). I think it would be better if dices, sound and number are all synced. Maybe speed up the dices a little bit, and slow down showing the number a little?

Thanks again!

**Comment by Sothatsit** [comment]
I've actually just sped up the dice in the last update! :) I'll try this out

**Comment by Sothatsit** [comment]
I've tried different variations of this, but of all of them I prefer it as it is now. It gives users more time to consider their moves, and is clear. It also causes few visual changes throughout the dice rolling, which I think is nicer.

I tried all of the following:
- Only set the number after all dice have been selected
- Use the placeholder "-" instead of "0" when the dice is rolling
- Randomise the placeholder while the dice are rolling
